version: "3"
services:
  client:
    build: 
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./Client/.env
    volumes:
      - ./Client:/app
    command: npm run dev
  
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./Server/.env
    volumes:
      - ./Server:/app
    command: npm run dev